export const SET_CATEGORIES = 'SET_CATEGORIES';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
