export const SET_DATE_FROM = 'SET_DATE_FROM';
export const SET_DATE_TO = 'SET_DATE_TO';

export const SET_START_VIEW_MAP_LATITUDE = 'SET_START_VIEW_MAP_LATITUDE';
export const SET_START_VIEW_MAP_LONGITUDE = 'SET_START_VIEW_MAP_LONGITUDE';
